# Site Settings
################
title: 'VICC'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'A Flexible Theme for Jekyll'

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: 'Organization website for the Variant Interpretation for Cancer Consortium (VICC), a driver project of the Global Alliance for Genomics and Health'

# The credits show up in the includes/_footer.html
credits: '<p>Created with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on the <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a> theme.</p>'

# Main author of the website
# See > authors.yml
author: "Alex H. Wagner, Ph.D."

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'https://cancervariants.org'
baseurl: ''

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: 'https://github.com/genome/vicc/edit/master/'

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: 'https://cancervariants.org/images/'


# Logo size is 600x80 pixels
logo: "VICC_no_text_mint.png"

# Plugins
plugins:
  - jekyll-asciidoc
  - jekyll-gist
  - jekyll-redirect-from

redirects: yes

# Collections
collections_dir: /collections/
collections:
  leadership:
    output: true
    sort_by: name
    permalink: /leadership/:path/
  standards:
    output: true
    sort_by: date
    permalink: /research/standards/:path/
  manuscripts:
    output: true
    sort_by: date
    permalink: /research/manuscripts/:path/
  event_presentations:
    sort_by: title
  presentations:
    output: true
    sort_by: date
    permalink: /presentations/:path/
  meetings:
    output: true
    sort_by: number
    meetings: /meetings/:path/

# Pagination
############
#paginate: 5                      # Paginates all X entries
#paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work


# Theme works best with Kramdown (using the table of contents function)
markdown           : kramdown
permalink          : /:categories/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']

# Exclude these files from your production _site
exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - INSTALL.md
  - vendor
  - .gitignore


# The language setting is used in /includes/header.html for html-settings
language: 'en'


# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]


# Default
##############

defaults:
  -
    scope:
      path: ''
    values:
      header: none
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: Alex     # Default author for pages
  -
    scope:
      path: ''
      type: 'presentations'
    values:
      type: 'presentation'
      layout: 'page'
  -
    scope:
      path: ''
      type: 'meetings'
    values:
      type: 'meeting'
      layout: 'page'
  -
    scope:
      path: ''
      type: 'standards'
    values:
      layout: 'research_product'
      status: 'draft'
      type: 'standard'
  -
    scope:
      path: ''
      type: 'manuscripts'
    values:
      layout: 'research_product'
      status: 'draft'
      type: 'article'
  -
    scope:
      path: ''
      type: 'leadership'
    values:
      layout: 'person'

# Favicons
#############

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'

# Social Media
##################

socialmedia:
  twitter: cancervariants

# Sass
##########

sass:
  sass_dir : _sass
  style    : :compressed


# Analytics
############

google_analytics_tracking_id: UA-107731206-1

# ASCIIDoctor
#############

asciidoctor-enabled: false
asciidoctor:
  description:
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font
